# Generated by Django 4.2.7 on 2023-11-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_room_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='planet',
            new_name='race',
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.CharField(default='Earth', max_length=400),
            preserve_default=False,
        ),
    ]
