# Generated by Django 4.2.7 on 2023-11-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_planet_person_race_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='campus',
            field=models.CharField(default='Marseille', max_length=128),
        ),
    ]
