# Generated by Django 4.2.7 on 2023-11-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.CharField(blank=True, default='images/profile.png', max_length=400),
        ),
    ]
