# Generated by Django 4.2.7 on 2023-11-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_person_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='race',
            new_name='planet',
        ),
    ]
